name: 'Docker Login Build Tag Push'

author: 'Danstan Onyango - Zemuldo'

description: 'Build, Tag and Push images to Registry'

inputs:
  image_name: 
    description: "Docker Image Name"
  image_tag:
    description: "Docker Image Tag"

runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{ inputs.image_name }}
    - ${{ inputs.repo_name }}
    - ${{ inputs.image_tag }}
    - ${{ inputs.docker_dir }}
    - ${{ inputs.docker_target }}
    - ${{ inputs.build_arg1 }}
    - ${{ inputs.build_arg2 }}
    - ${{ inputs.build_arg3 }}
    - ${{ inputs.build_arg4 }}
    - ${{ inputs.build_arg5 }}
    - ${{ inputs.build_arg6 }}
    - ${{ inputs.build_arg7 }}
    - ${{ inputs.build_arg8 }}
    - ${{ inputs.build_arg9 }}
    
branding:
  icon: 'upload-cloud'  
  color: 'blue'
