name: 'Publish to GCR'

description: 'Build, Tag and Push images to GCR'

inputs:
  image_name: 
    description: "Docker Image Name"
  image_tag:
    description: "Docker Image Tag"

runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{ inputs.image_name }}
    - ${{ inputs.image_tag }}
